# configurations that start and link containers
version: '3'
# services that we will ne running

services:
  sep_back_up: 
    # we add the directory in which the project exists
    build: .
    # host address
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    # volumes save data - data is lost when docker is shut down
    ports:
      - "8000:8000"
    depends_on:
      - db



  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_init.py:/app

  mongo-init:
    build:
      context: .
    depends_on:
      - db
    command: python mongo_init.py
