# configurations that start and link containers
version: '3'
# services that we will be running

services:
  sep_back_up: 
    # we add the directory in which the project exists
    build: .
    # host address
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    # volumes save data - data is lost when docker is shut down
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_init.py:/app
      - mongodb_data:/data/db

  mongo-init:
    build:
      context: .
    depends_on:
      - db
    command: python mongo_init.py

# Define the named volume for MongoDB data persistence
volumes:
  mongodb_data: